-- Hybrid Graph RAG schema on YugabyteDB 2026.1.
--
-- Two complementary stores over the SAME distributed SQL database:
--   1. pgvector  -> semantic similarity over document chunks
--   2. MAGE      -> entity/relationship graph for multi-hop traversal
--
-- A chunk row and the graph nodes it mentions are linked by chunk_id, so a
-- vector hit can pull in graph context and vice-versa.

-- ---------------------------------------------------------------------------
-- Extensions
--   * vector       - pgvector similarity search
--   * mage         - YugabyteDB's Apache AGE-compatible graph engine (2026.1+).
--                    Requires the gflag ysql_yb_enable_mage=true on master and
--                    tserver. MAGE lives under the `mag_catalog` schema (the
--                    YugabyteDB equivalent of upstream AGE's `ag_catalog`).
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS mage CASCADE;

-- ---------------------------------------------------------------------------
-- Vector store: one row per document chunk
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doc_chunks (
    chunk_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id      text         NOT NULL,
    chunk_no    int          NOT NULL,
    content     text         NOT NULL,
    -- 1024 dims = Bedrock Titan Text Embeddings V2 native width (also the
    -- width of the no-creds hash fallback embedder), keeping the schema
    -- runnable with or without cloud access.
    embedding   vector(1024) NOT NULL
);

-- HNSW index for fast approximate cosine search (YugabyteDB vector index).
CREATE INDEX IF NOT EXISTS doc_chunks_embedding_idx
    ON doc_chunks USING ybhnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- Graph store: a single named graph with Entity nodes and RELATED_TO edges.
--
-- IMPORTANT MAGE quirks (YugabyteDB 2026.1):
--   * Put mag_catalog on the search_path and call create_graph / create_vlabel
--     / create_elabel UNQUALIFIED. Schema-qualifying the call (or wrapping it
--     in an explicit BEGIN/COMMIT) raises
--     "Commit separate ddl txn called when not in a separate DDL transaction".
--   * Graph names must be at least 3 characters.
-- ---------------------------------------------------------------------------
SET search_path = mag_catalog, "$user", public;

SELECT create_graph('knowledge_graph');
SELECT create_vlabel('knowledge_graph', 'Entity');
SELECT create_elabel('knowledge_graph', 'RELATED_TO');
